### PR TITLE
Add networkx tutorial notebooks for functional network analysis

### PR DESCRIPTION
**Pull request by mammykins**

### CODE REVIEW

**Comment by mammykins** [comment]
@ff-l shall we consider merging this, as the spike notebooks are complete?

**Comment by ff-l** [comment]
@mammykins Okay, let me make sure I've got everything synced up on my end, will start review then.

**Comment by mammykins** [comment]
I'll review your notebooks as well

**Comment by mammykins** [comment]
Some of the notebooks are lacking annotation, can we include an introductory paragraph about what the notebook achieves? (the notebook names are informative but let's add extra detail with some markdown, see the networkx tutorial notebook for an example)

**Comment by mammykins** [comment]
The network metrics notebook has some repetition of the networkx tutorial notebook. Perhaps it's worth creating a notebook just for the search api aspect? @ff-l

**Comment by ff-l** [comment]
We can leave the annotation for a later date, I think. I can add short comments/documentation. Why the intro paragraph? For potential new users/devs?

**Comment by mammykins** [comment]
Mat to fix the above, given permission from @ff-l

**Pull request merged**
